### PR TITLE
Prime font replaced with Mina font

### PR DESCRIPTION
**Pull request by thubalek**
Prime font used in the application performs bad with some letter pairs. See screenshot

image

Some letters are missing at all (see :

image

I tried to find free similar font that works well.  I'm proposing to replace Prime with [Mina font](https://fonts.google.com/specimen/Mina). 

Here is side by side comparison of screen:

Before:
image

After:
image
 
 I changed Android app only, didn't touch WearOS app.

### CODE REVIEW

**Comment by paymicro** [comment]
Mina font is printed text in Russian
image
The absence of symbols is more critical. Primo has been modified here and symbols have been added to it through a special program.

**Comment by paymicro** [comment]
Write down which letters are missing and which ones should look different. Then the font can be corrected without replacing it with another one.

**Comment by thubalek** [comment]
I didn't realize that Cyrilic is not supported on Mina. Sorry about that.

Adding/fixing fonts to Prime should be Ok. 

Please make sure these letters are included for Czech Language

```
ÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ
áčďéěíňóřšťúůýž
```
It looks like `ČĎĚŇŘŤŮŽ` and `čďěňřťůž` are not from original font. 

image

image


Also `í` has acute at wrong place (slightly shifted).

Also please look at `j` letter. I looks somehow shifted.

image

Other letters seems fine.

**Comment by paymicro** [comment]
image
correct?

**Comment by thubalek** [comment]
I'm closing this pull request in favor of a pull request #451

**Pull request closed without merging**
