### PR TITLE
VeteranAdapter Kotlin refactor

### PR DESCRIPTION
**Pull request by nathan234**
Preparing this for the new Veteran Lynx

### CODE REVIEW

**Comment by paymicro** [comment]
why is this necessary?

**Comment by nathan234** [comment]
It is not necessary.

**Comment by paymicro** [comment]
I don't see any reason why a new model can't be added without refactoring

**Comment by nathan234** [comment]
You're right, it doesn't. So you don't want this code merged then?

**Comment by paymicro** [comment]
Yes. A clear reason is needed for such a change. As you can see, all adapters are written in java. This is an important code.

**Comment by nathan234** [comment]
So would you prefer a Java PR to change the Veteran Adapter? Perhaps a draft? The voltage is going to be incorrect on the Lynx

**Pull request closed without merging**
